//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WithingsBodyScale.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WithingsBodyScale.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Online-Waage.
        /// </summary>
        internal static string de_UI_SettingsPage_labelBannerText_Text {
            get {
                return ResourceManager.GetString("de_UI_SettingsPage_labelBannerText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La báscula conectada a Internet.
        /// </summary>
        internal static string es_UI_SettingsPage_labelBannerText_Text {
            get {
                return ResourceManager.GetString("es_UI_SettingsPage_labelBannerText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La balance connectée à internet.
        /// </summary>
        internal static string fr_UI_SettingsPage_labelBannerText_Text {
            get {
                return ResourceManager.GetString("fr_UI_SettingsPage_labelBannerText_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap horizontal_banner {
            get {
                object obj = ResourceManager.GetObject("horizontal_banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_12_MenuCascadeArrowDown {
            get {
                object obj = ResourceManager.GetObject("Image_12_MenuCascadeArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La bilancia connessa ad Internet.
        /// </summary>
        internal static string it_UI_SettingsPage_labelBannerText_Text {
            get {
                return ResourceManager.GetString("it_UI_SettingsPage_labelBannerText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Earliest.
        /// </summary>
        internal static string MultipleEntriesUpdateStyles_Earliest_Text {
            get {
                return ResourceManager.GetString("MultipleEntriesUpdateStyles_Earliest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Highest.
        /// </summary>
        internal static string MultipleEntriesUpdateStyles_Highest_Text {
            get {
                return ResourceManager.GetString("MultipleEntriesUpdateStyles_Highest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Latest.
        /// </summary>
        internal static string MultipleEntriesUpdateStyles_Latest_Text {
            get {
                return ResourceManager.GetString("MultipleEntriesUpdateStyles_Latest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Lowest.
        /// </summary>
        internal static string MultipleEntriesUpdateStyles_Lowest_Text {
            get {
                return ResourceManager.GetString("MultipleEntriesUpdateStyles_Lowest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Withings weegschaal voor.
        /// </summary>
        internal static string nl_UI_SettingsPage_labelBannerText_Text {
            get {
                return ResourceManager.GetString("nl_UI_SettingsPage_labelBannerText_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap progress_1 {
            get {
                object obj = ResourceManager.GetObject("progress_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress_10 {
            get {
                object obj = ResourceManager.GetObject("progress_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress_11 {
            get {
                object obj = ResourceManager.GetObject("progress_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress_12 {
            get {
                object obj = ResourceManager.GetObject("progress_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress_2 {
            get {
                object obj = ResourceManager.GetObject("progress_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress_3 {
            get {
                object obj = ResourceManager.GetObject("progress_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress_4 {
            get {
                object obj = ResourceManager.GetObject("progress_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress_5 {
            get {
                object obj = ResourceManager.GetObject("progress_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress_6 {
            get {
                object obj = ResourceManager.GetObject("progress_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress_7 {
            get {
                object obj = ResourceManager.GetObject("progress_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress_8 {
            get {
                object obj = ResourceManager.GetObject("progress_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap progress_9 {
            get {
                object obj = ResourceManager.GetObject("progress_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scale_watermark_large {
            get {
                object obj = ResourceManager.GetObject("scale_watermark_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string UI_ConfigureWizard_Page_AccountInfo_passwordLabel_Text {
            get {
                return ResourceManager.GetString("UI_ConfigureWizard_Page_AccountInfo_passwordLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account information.
        /// </summary>
        internal static string UI_ConfigureWizard_Page_AccountInfo_Title {
            get {
                return ResourceManager.GetString("UI_ConfigureWizard_Page_AccountInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the account (email) and password you use to connect to the my.withings.com website. The password you enter below will be used only once to establish a connection and will not be stored on this computer..
        /// </summary>
        internal static string UI_ConfigureWizard_Page_AccountInfo_topTextLabel_Text {
            get {
                return ResourceManager.GetString("UI_ConfigureWizard_Page_AccountInfo_topTextLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieval complete. Click &quot;Finish&quot; to import history into your logbook..
        /// </summary>
        internal static string UI_ConfigureWizard_Page_ImportHistory_Complete_Text {
            get {
                return ResourceManager.GetString("UI_ConfigureWizard_Page_ImportHistory_Complete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieval failed..
        /// </summary>
        internal static string UI_ConfigureWizard_Page_ImportHistory_Failed_Text {
            get {
                return ResourceManager.GetString("UI_ConfigureWizard_Page_ImportHistory_Failed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No measurements..
        /// </summary>
        internal static string UI_ConfigureWizard_Page_ImportHistory_RetrievedNone_Text {
            get {
                return ResourceManager.GetString("UI_ConfigureWizard_Page_ImportHistory_RetrievedNone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ {1} to {2} ] Number of measurements: {0}..
        /// </summary>
        internal static string UI_ConfigureWizard_Page_ImportHistory_RetrievedRange_Text {
            get {
                return ResourceManager.GetString("UI_ConfigureWizard_Page_ImportHistory_RetrievedRange_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ {0} ] One measurement..
        /// </summary>
        internal static string UI_ConfigureWizard_Page_ImportHistory_RetrievedSingle_Text {
            get {
                return ResourceManager.GetString("UI_ConfigureWizard_Page_ImportHistory_RetrievedSingle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing history.
        /// </summary>
        internal static string UI_ConfigureWizard_Page_ImportHistory_Title {
            get {
                return ResourceManager.GetString("UI_ConfigureWizard_Page_ImportHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while your history is retrieved..
        /// </summary>
        internal static string UI_ConfigureWizard_Page_ImportHistory_topTextLabel_Text {
            get {
                return ResourceManager.GetString("UI_ConfigureWizard_Page_ImportHistory_topTextLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review sync settings.
        /// </summary>
        internal static string UI_ConfigureWizard_Page_ImportSettings_Title {
            get {
                return ResourceManager.GetString("UI_ConfigureWizard_Page_ImportSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user profile.
        /// </summary>
        internal static string UI_ConfigureWizard_Page_SelectUser_Title {
            get {
                return ResourceManager.GetString("UI_ConfigureWizard_Page_SelectUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withings Body Scale Sync Configuration Wizard.
        /// </summary>
        internal static string UI_ConfigureWizard_Title {
            get {
                return ResourceManager.GetString("UI_ConfigureWizard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account:.
        /// </summary>
        internal static string UI_LogbookSettingsPanel_accountLabel_Text {
            get {
                return ResourceManager.GetString("UI_LogbookSettingsPanel_accountLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import ambiguous entries:.
        /// </summary>
        internal static string UI_LogbookSettingsPanel_ambiguousLabel_Text {
            get {
                return ResourceManager.GetString("UI_LogbookSettingsPanel_ambiguousLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to deactivate the Withings Body Scale sync?.
        /// </summary>
        internal static string UI_LogbookSettingsPanel_Deactivate_Text {
            get {
                return ResourceManager.GetString("UI_LogbookSettingsPanel_Deactivate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Sync.
        /// </summary>
        internal static string UI_LogbookSettingsPanel_Deactivate_Title {
            get {
                return ResourceManager.GetString("UI_LogbookSettingsPanel_Deactivate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string UI_LogbookSettingsPanel_deactivateButton_Text {
            get {
                return ResourceManager.GetString("UI_LogbookSettingsPanel_deactivateButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import height entries:.
        /// </summary>
        internal static string UI_LogbookSettingsPanel_heightLabel_Text {
            get {
                return ResourceManager.GetString("UI_LogbookSettingsPanel_heightLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of Last Connection.
        /// </summary>
        internal static string UI_LogbookSettingsPanel_lastConnectionLabel_Text {
            get {
                return ResourceManager.GetString("UI_LogbookSettingsPanel_lastConnectionLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import manual entries:.
        /// </summary>
        internal static string UI_LogbookSettingsPanel_manualLabel_Text {
            get {
                return ResourceManager.GetString("UI_LogbookSettingsPanel_manualLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For multiple entries on one day:.
        /// </summary>
        internal static string UI_LogbookSettingsPanel_multipleEntriesLabel_Text {
            get {
                return ResourceManager.GetString("UI_LogbookSettingsPanel_multipleEntriesLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string UI_LogbookSettingsPanel_optionsLabel_Text {
            get {
                return ResourceManager.GetString("UI_LogbookSettingsPanel_optionsLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconfigure....
        /// </summary>
        internal static string UI_LogbookSettingsPanel_reconfigureButton_Text {
            get {
                return ResourceManager.GetString("UI_LogbookSettingsPanel_reconfigureButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update BMI:.
        /// </summary>
        internal static string UI_LogbookSettingsPanel_updateBMILabel_Text {
            get {
                return ResourceManager.GetString("UI_LogbookSettingsPanel_updateBMILabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        internal static string UI_LogbookSettingsPanel_userLabel_Text {
            get {
                return ResourceManager.GetString("UI_LogbookSettingsPanel_userLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure....
        /// </summary>
        internal static string UI_SettingsPage_configureButton_Text {
            get {
                return ResourceManager.GetString("UI_SettingsPage_configureButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Internet connected Body Scale.
        /// </summary>
        internal static string UI_SettingsPage_labelBannerText_Text {
            get {
                return ResourceManager.GetString("UI_SettingsPage_labelBannerText_Text", resourceCulture);
            }
        }
    }
}
